version: '3'

services:
  database:
    restart: unless-stopped
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - laravel

  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8081:8000"
    networks:
      - laravel
    depends_on:
      - database
    environment:
      - "DB_CONNECTION=mysql"
      - "DB_HOST=database"
      - "DB_PORT=3306"
      - "DB_DATABASE=laravel"
      - "DB_USERNAME=laraveluser"
      - "DB_PASSWORD=laravelpassword"


networks:
  laravel:
